# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlustairCli < Formula
  desc "Scan all images in your Kubernetes cluster with Trivy and check your configuration with Kubeaudit"
  homepage "https://github.com/klustair/klustair-cli"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.7.1/klustair-cli_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "c52024cf576c32f99267c31b41596416d046a60dc408042adbfa8e92cd3c7a57"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.7.1/klustair-cli_0.7.1_Darwin_arm64.tar.gz"
      sha256 "84e8c15b2bd2afc4699c0a7a980c67faef85978ad8c52ef3048b5fa72f5d5b94"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.7.1/klustair-cli_0.7.1_Linux_x86_64.tar.gz"
      sha256 "ce3dd3fb276c2f4493cbdad42ae581a36bd20135ae3dc67bf04ce421db729e93"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.7.1/klustair-cli_0.7.1_Linux_arm64.tar.gz"
      sha256 "6aa9f7ec976111c76b559ea1279a6675f6e8ef2d788e888a6158ca6a945a03be"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  test do
    system "#{bin}/klustair-cli", "--version"
  end
end
