# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlustairCli < Formula
  desc "Scan all images in your Kubernetes cluster with Trivy and check your configuration with Kubeaudit"
  homepage "https://github.com/klustair/klustair-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "c72ef96b0cd1f2e071c9c7b1bfe0dff5495079966a7e652973d35f2030a84093"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Darwin_arm64.tar.gz"
      sha256 "cc9c169f28b439a390b074dbcf4c4173a0120ee8ecc4a52ae57fc2c9a8fb9f65"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "6a22e5e9e8ffeb6feee6b6bd2e43f2d8d2db79a944da68c6239952a20e705e34"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Linux_arm64.tar.gz"
      sha256 "7a8cb971fbb6d37b3febdd514d437cea245957262b10f3bb7cb5b7965176dac0"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  test do
    system "#{bin}/klustair-cli", "--version"
  end
end
