# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlustairCli < Formula
  desc "Scan all images in your Kubernetes cluster with Trivy and check your configuration with Kubeaudit"
  homepage "https://github.com/klustair/klustair-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Darwin_arm64.tar.gz"
      sha256 "7d8ecd39cacfdba9b4d2c391c34ff65e2b71d6fac7bd1cbd437b165ab94e251c"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "b59c6213994d07abaa200bb662b902e09a02695803c8075b321911cd5ddbc3d5"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "21f1bb88239ae24ac3a5cce2cf6b1f4d723a079454e1d0f072e62a8a52dfe024"

      def install
        bin.install "klustair-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klustair/klustair-cli/releases/download/v0.0.1/klustair-cli_0.0.1_Linux_arm64.tar.gz"
      sha256 "1d8068f1eecaf8fbe5fd95dcaaeeaf7a1a50db54e1ddc10140442618de8eb6b0"

      def install
        bin.install "klustair-cli"
      end
    end
  end

  test do
    system "#{bin}/klustair-cli", "--version"
  end
end
